version: '3.4'

services:
  webapia:
    image: ${DOCKER_REGISTRY-}webapia
    build:
      context: .
      dockerfile: WebApiA/Dockerfile

  webapib:
    image: ${DOCKER_REGISTRY-}webapib
    build:
      context: .
      dockerfile: WebApiB/Dockerfile


  webapic:
    image: ${DOCKER_REGISTRY-}webapic
    build:
      context: .
      dockerfile: WebApiC/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: 
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
        
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.1
    restart: always
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    
volumes: 
  elasticsearch-data-volume:
    driver: local

